NS_01001DC01486A000_Tsukihime.js

Fixes:
```
Error: Error: Module ./libyuzu.js not found!
```

fix libYuzu import on tsukihime

---

NS_010012A017F18000_Mahoyo.js

Only offset had to be changed since it's the same engine.

Add support for Mahoyo

---

PC_Steam_Unity_AKAIITO.js
PC_Steam_Unity_AOISHIRO.js

I wasn't sure if there were any code standards I should follow. Let me know if I need to change anything

Add AKAIITO and AOISHIRO　

---

NS_010003F003A34000_Pokemon_Let's_Go_Pikachu.js
NS_010057E00AC56000_Dragon's_Dogma.js
NS_010065301A2E0000_Star_Ocean_The_Second_Story_R.js
NS_0100CB9018F5A000_Another_Code_Recollection.js

I'm adding:
Another Code: Recollection
Star Ocean: The Second Story R
Pokémon Lets Go Pikachu
Dragon's Dogma

Add 4 Switch games

---

NS_0100B5800C0E4000_Reine_des_Fleurs.js

Add Reine des Fleurs Switch

---

NS_0100F4401940A000_Master_Detective_Archives_Rain_Code.js

Add Master Detective Archives Rain Code for Yuzu

Add Master Detective Archives Rain Code Switch

---

NS_0100DA101D9AA000_Utsusemi_no_Meguri.js
PSVita_PCSG01023_Tsuihou_Senkyo.js
PSVita_PCSG01194_Sanzen_Sekai_Yuugi_Re_Multi_Universe_Myself.js

Add Tsuihou Senkyo
Add Sanzen Sekai Yuugi ~MultiUniverse Myself~

Adding new PSVita scripts

---

NS_01000200194AE000_Majestic _Majolical.js

Revert "Fixed heroine name displayed at the bottom and a minor fix"

---

PC_Steam_Unity_Paranormasight.js

A script for Paranormasight for PC Steam.

Add Paranormasight for PC Steam.

---

NS_010024200E00A000_Uta_no_Prince_sama_Repeat_Love.js
NS_01003FE00E2F8000_Spade_no_Kuni_no_Alice.js
NS_01007010157B4000_Galleria_no_Chika_Meikyuu_to_Majo_no_Ryodan.js
NS_0100771013FA8000_Ken_ga_Kimi_for_S.js
NS_01008BE016CE2000_Ikemen_Sengoku_Toki_o_Kakeru_Koi.js
NS_0100A1200CA3C000_Chou_no_Doku_Hana_no_Kusari_Taishou_Tsuya_Koi_Ibun.js
NS_0100ADC014DA0000_AIR.js
NS_0100BD7015E6C000_Kiss_Bell.js
NS_0100BE40138B8000_Fata_morgana_no_Yakata.js
NS_0100E1E00E2AE000_Hakuouki_Shinkai_Tsukikage_no_Shou.js

Adding:
AIR	#26
Ken ga Kimi for S	 #239 #32
Uta no Prince-sama Repeat Love #117 #9
Ikemen Sengoku Toki o Kakeru Koi #252 #42
Hakuouki Shinkai: Tsukikage no Shou #39
Galleria no Chika Meikyuu to Majo no Ryodan #23 #208
Spade no Kuni no Alice Wonderful White World #12
Kiss Bell - Let's sound the kissing-bell of the promise #77
Chou no Doku Hana no Kusari Taishou Tsuya Koi Ibun #8 #287
Fata morgana no Yakata Dreams of the Revenants Edition #22 #132

Adding 10 new switch Games/VNs

---

PC_Steam_Unity_Shin.Megami.Tensei.III.Nocturne.HD.Remaster.js

Adding script for Shin Megami Tensei III Nocturne HD Remaster for PC Steam.

Add Shin Megami Tensei III Nocturne HD Remaster

---

NS_01001C1009892000_The_World_Ends_With_You.js
NS_010039B015CB6000_Eiyuden_Chronicle_Rising.js
NS_010043B013C5C000_NEO_The_World_Ends_With_You.js
NS_01006BD0095F4000_Shin_Megami_Tensei_V.js
NS_01008A3016162000_Etrian_Odyssey_I.js
NS_0100B0C016164000_Etrian_Odyssey_II.js
NS_0100BD4014D8C000_AI_The_Somnium_Files _nirvanA_Initiative.js
NS_0100C4E013E5E000_Ni_no_Kuni_II_Revenant_Kingdom.js
NS_0100CBA014014000_Tantei_Bokumetsu.js
NS_0100D32015A52000_Etrian_Odyssey_III.js
NS_0100D7800E9E0000_Trials_of_Mana.js
NS_0100EDD018032000_Harvestella.js

Adding:
AI: The Somnium Files - nirvanA Initiative
Ni no Kuni II: Revenant Kingdom
Shin Megami Tensei V
Trials of Mana (2020) #285

Add 12 new Switch games

---

NS_0100FC2019346000_Princess_Arthur.js
PSVita_PCSG00389_Binary_Star.js
PSVita_PCSG01282_Shinigami_to_Shoujo.js

Adding Princess Arthur: #57  #253

Adding new Switch VN

---

NS_0100A8401A0A8000_Natsumon-20th_Century_Summer_Vacation.js

adds script for Natsumon! 20th century vacation
Closes this issue: https://github.com/0xDC00/scripts/issues/226

add script for nintendo switch game Natsumon!

---

NS 010045C0109F2000 VARIABLE BARRICADE NS.js

Filling this request.
https://github.com/0xDC00/scripts/issues/326

Add Variable Barricade (Switch)

---

NS_0100F7401AA74000_Getsuei_no_Kusari_Sakuran_Paranoia.js
PSVita_PCSG00410_Nekketsu_Inou_Bukatsu-tan_Trigger_Kiss.js

Add  Getsuei no Kusari Sakuran Paranoia (switch)
Add Nekketsu Inou Bukatsu-tan Trigger Kiss (Vita)

Adding new scripts

---

PC_Steam_Unity_AI_The_Somnium_Files.js
PC_Steam_Unity_AI_The_Somnium_Files_-_nirvanA_Initiative.js

Add scripts for AI: The Somnium Files and AI: The Somnium Files - nirvanA Initiative. Both games use Unity. The sequel uses IL2CPP, but the script still works on both games.
This pull request also closes #269.
Screenshot:

Add scripts for AI: The Somnium Files 1 & 2 (Steam)

---

PC_Steam_Chrono_Trigger.js

Add script for Chrono Trigger (Steam)

---

PC_Steam_Zero_Escape_The_Nonary_Games_999.js
PC_Steam_Zero_Escape_The_Nonary_Games_Virtue's_Last_Reward.js
PC_Steam_Zero_Escape_Zero_Time_Dilemma.js

This pull request adds scripts for the following games:
- Zero Escape: The Nonary Games - Nine Hours, Nine Persons, Nine Doors (999)
- Zero Escape: The Nonary Games - Virtue’s Last Reward
- Zero Escape: Zero Time Dilemma
Screenshot:

Add scripts for Zero Escape Series (Steam)

---

NS_0100F8A017BAA000_Sen _no _Hatou_Tsukisome _no _Kouki.js
PSVita_PCSG00216_Rui_wa_Tomo_o_Yobu.js
PSVita_PCSG00448_MARGINAL_#4_IDOL_OF_SUPERNOVA.js
PSVita_PCSG00648_Tsuki_ni_Yorisou_Otome_no_Sahou.js
PSVita_PCSG01008_MARGINAL_#4_ROAD_TO_GALAXY.js

Add Sen no Hatou, Tsukisome no Kouki (Switch)
Add Rui wa Tomo o Yobu (Vita)
Add Tsuki ni Yorisou Otome no Sahou (Vita)
Add MARGINAL#4 Series  #314

Add new Scripts

---

libMono.js

There is an issue with games running older versions of Unity, when attaching to the game, the following error will show show in the agent console:
This happens without even specifying a hook, but just requiring `libMono.js`:
```js
const Mono = require('./libMono.js');
```
This is due to the fact that in these older Unity versions, `mono_thread_attach` attach gets exported from not only `mono.dll`, but also the game's `.exe` file. This causes `libMono.js` to set the game's module to its `.exe` file instead of `mono.dll`.
I tested with the following Unity games. In the first three games listed, `libMono.js` finds the incorrect export:
| Game                                          | Export (Before)                                                               | Status | Unity Version |
| …

Resolve issue with libMono.js on older versions of Unity

---

NS_01001EF017BE6000_Rune_Factory_3_Special.js
NS_01002C0008E52000_Tales_of_Vesperia.js
NS_010055D009F78000_Fire_Emblem_Three_Houses.js
NS_010056F00C7B4000_Bravely_Default_II.js
NS_010074F013262000_Xenoblade_Chronicles_3.js
NS_0100CC401A16C000_Ys_X_Nordics.js
NS_0100EF00134F4000_Dragon_Ball_Z_Kakarot.js
NS_0100FDB00AA80000_Layton’s_Mystery_Journey.js

Adding:
Ys X: Nordics
Tales of Vesperia #284
Bravely Default II
Dragon Ball Z: Kakarot
Rune Factory 3 Special #149
Xenoblade Chronicles 3 #224
Layton’s Mystery Journey
Fire Emblem: Three Houses #134

Adding 8 Switch games

---

NS_0100DA201E0DA000_Akuyaku_Reijou_wa_Ringoku_no_Outaishi_ni_Dekiai_Sareru.js

Add Akuyaku Reijou wa Ringoku no Outaishi ni Dekiai Sareru  #401

Add new switch games

---

NS_01002AE00F442000_FLOWERS_Les_Quatre_Saisons.js

Add NS_01002AE00F442000_FLOWERS_Les_Quatre_Saisons for Yuzu.

Add FLOWERS Les Quatre Saisons

---

NS_010060800B7A8000_BUSTAFELLOWS.js

Add NS_010060800B7A8000_BUSTAFELLOWS for Yuzu

Add BUSTAFELLOWS for Yuzu

---

NS_010007500F27C000_Detective_Pikachu_Returns.js
NS_0100217014266000_Dragon_Quest_Treasures.js
NS_010027100C79A000_Rune_Factory_4_Special.js
NS_01002DA013484000_The_Legend_of_Zelda_Skyward_Sword.js
NS_010072000BD32000_World_of_Final_Fantasy.js
NS_010080C01AA22000_Tokyo_Xanadu_eX+.js
NS_01009B50139A8000_DORAEMON_STORY_OF_SEASONS_Friends_of_the_Great_Kingdom.js
NS_0100CB700D438000_Monster_Hunter_Stories_2.js

Adding:
Tokyo Xanadu eX+
Rune Factory 4 Special
Dragon Quest Treasures
Detective Pikachu Returns
World of Final Fantasy Maxima
The Legend of Zelda: Skyward Sword
Monster Hunter Stories 2: Wings of Ruin
Doraemon Story of Seasons: Friends of the Great Kingdom

Adding 8 new switch games

---

NS_01001B900C0E2000_Moujuutsukai_to_Ouji-sama_Flower_＆_Snow.js
PSVita_PCSG00405_Reine_des_Fleurs.js

Add Moujuutsukai to Ouji-sama Flower & Snow  #293  #387

Add new switch script

---

PSVita_PCSG00911_Re_Birthday_Song_Koi_o_Utau_Shinigami.js
PSVita_PCSG00912_Un_Birthday_Song_Ai_o_Utau_Shinigami.js

Re:Birthday Song Koi o Utau Shinigami
Un:Birthday Song Ai o Utau Shinigami

Adding scripts for the Birthday Song Series (PSvita)

---

NS_010027401A2A2000_Utakata_no_Uchronia.js

Requested by @MelonCakey:
https://github.com/0xDC00/scripts/commit/4dc98e93bab6c88f2d1ce298f0e1f07e5e5e2ece#commitcomment-141627926

Add choices hook for Utakata no Uchronia

---

NS_0100086005EDC000_Naruto_Shippuden_Ultimate_Ninja_Storm_Trilogy.js
NS_010014D01216E000_Rune_Factory_5.js
NS_01003F800CF5C000_Naruto_Shippuden_Ultimate_Ninja_Storm_4.js
NS_01004DF01DD2A000_Eiyuden_Chronicle_Hundred_Heroes.js
NS_0100A77018EA0000_Dragon_Quest_Monsters_The_Dark_Prince.js
NS_0100C0000CEEA000_Yo-kai_Watch_1.js

Adding:
Yo-kai Watch 1
Rune Factory 5
Eiyuden Chronicle: Hundred Heroes
Dragon Quest Monsters: The Dark Prince
Naruto Shippuden: Ultimate Ninja Storm Trilogy (1, 2 and 3)
Naruto Shippuden: Ultimate Ninja Storm 4 ROAD TO BORUTO

Adding new switch games

---

PSVita_PCSG00776_Muv_Luv.js

Add Muv-Luv script for PSVita (PCGS00776)

---

libUI.js

This "library" script is used to easily add a UI and configuration into a game's script.
It supports the following:
- Configuration types:
- Text
- Number
- Checkbox
- Select
- Multi-Select
- Button
- Read-only configuration (useful for displaying info)
- Storage:
- Stores all configuration in `localStorage` so it user's configuration stays between reloads of Agent.
- Has an `ephemeral` configuration for fields that you never want to store (for example, the `Monitor` checkbox on the tracer script).
- Consistent styling:
- Uses Agent's styling, so it fits seamlessly into the UI.
- Sync configuration:
- The configuration will stay synced between script and the UI. The UI will notify the script if a configuration is updated in the UI, and the script will notify the UI if the configuration is …

Add libUI.js

---

NS_0100A62019078000_Temirana_Koku_no_Tsuiteru_Hime_to_Tsuitenai_Kishidan.js
PSVita_PCSG00389_Binary_Star.js
PSVita_PCSG00401_Sora_Yume.js
PSVita_PCSG00912_Un_Birthday_Song_Ai_o_Utau_Shinigami.js

Replaced the "dialogue" hook with a better one  because the old one couldnt extract the text whenever the MC talks for some reason

Changed hook of the main dialogue in Un_Birthday_Song_Ai_o_Utau_Shinigami.js and adding new scripts 

---

PC_Steam_Hajimari_no_Kiseki.js

Works for most dialogue and item/skills descriptions. I'll probably be adding and fixing things as I play through it.
Also, if anything on the code looks bad, please tell me as I kind of went along based on other scripts and my limited RE knowledge.
Screenshots:

Add Hajimari no Kiseki (Steam)

---

PC_Steam_Hajimari_no_Kiseki.js

Found out a bit more about the dialogue format of the game so I've updated the script to support more instances of dialogue.

Fixing some dialogue for Hajimari no Kiseki

---

NS_010095E01581C000_even_if_TEMPEST_Tsuranaru_Toki_no_Akatsuki.js
NS_010095E01581C000_even_if_TEMPEST_Yoiyami_ni_Kaku_Katariki_Majo.js
NS_0100DEF01D0C2000_even_if_TEMPEST_Tsuranaru_Toki_no_Akatsuki.js

Add:
even if TEMPEST: Yoiyami ni Kaku Katariki Majo #375 
even if TEMPEST: Tsuranaru Toki no Akatsuki #376

Add even if TEMPEST games

---

PC_Steam_Hajimari_no_Kiseki.js
PC_Steam_Unity_Moonless_Moon.js

Adds Moonless Moon and updates Hajimari no Kiseki to correctly print more dialogue instances.
Should close #525

Add Moonless Moon (Steam)

---

NS_01007AD01CB42000_Mistonia_no_Kibou.js
PSVita_PCSG01180_Tengai_ni_Mau_Iki_na_Hana

Tengai ni Mau #323 #464 
Mistonia #518

Add Tengai ni Mau

---

NS_0100EC001DE7E000_Hiiro_no_Kakera_Tamayorihime_Kitan_Omoiiro_no_Kioku.js

Adding  HIIRO NO KAKERA Tamayori Hime Kitan (Switch)

---

NS_010096000CA38000_Taishou_x_Alice_all_in_one.js
NS_0100B1F0123B6000_Taishou_x_Alice_HEADS_&_TAILS.js

Add:
Taishou x Alice all in one
Taishou x Alice: HEADS & TAILS

Add Taishou x Alice games

---

NS_010037500DF38000_Gensou_Manege.js

Add Gensou Manège

---

NS_010079200C26E000_Gensou_Kissa_Enchante.js

Add Gensou Kissa Enchanté / Cafe Enchante #389

Add Gensou Kissa Enchanté

---

NS_01002C00177AE000_Tengoku_Struggle_strayside.js

Add Tengoku Struggle -strayside- #83

Add Tengoku Struggle -strayside-

---

NS_010096000CA38000_Taishou_x_Alice_all_in_one.js
NS_0100B1F0123B6000_Taishou_x_Alice_HEADS_&_TAILS.js

I assumed that dialogues would have at most one delayed part until I found a character that pauses mid-speech twice, so these changes should help better handle those successive delayed parts.

Fix regex and delayed dialogue for Taishou x Alice

---

NS_0100FA001E160000_7scarlet.js

Add 7'scarlet

---

NS_0100EA100DF92000_Meiji_Katsugeki_Haikara_Ryuuseigumi.js

Add Meiji Katsugeki Haikara Ryuuseigumi

---

NS_010061300DF48000_Dairoku_Ayakashimori.js

Add Dairoku: Ayakashimori #257 
I've tested the dictionary hook on 31 entries and all of them printed fine

Add Dairoku: Ayakashimori

---

NS_010021D01474E000_Kimi_wa_Yukima_ni_Koinegau.js

Add Kimi wa Yukima ni Koinegau

Add Kimi wa Yukima ni Koinegau

---

NS_0100FA10185B0000_SympathyKiss.js

Add SympathyKiss / Sympathy Kiss

Add SympathyKiss

---

NS_0100F9D00C186000_Olympia_Soiree.js

I'm not sure how reliable the hook and my way of handling it is, but it works fine from what I've tested

Update Olympia Soiree with dictionary hooks

---

NS_0100CEF0152DE000_Charade_Maniacs.js

Add Charade Maniacs / CharadeManiacs

Add Charade Maniacs

---

NS_0100DEF01D0C6000_Hanaemu_Kare_to_&_bloom.js

Add Hanaemu Kare to & bloom

---

NS_01004E5017C54000_Dance_with_Devils.js

Add Dance with Devils #412 #546

Add Dance with Devils

---

NS_01003BB01DF54000_My9Swallows_TOPSTARS_LEAGUE.js

Add My9Swallows TOPSTARS LEAGUE

---

NS_010088B01A8FC000_Radiant_Tale_Fanfare.js
NS_0100925014864000_Radiant_Tale.js

Add Radiant Tale ~Fanfare!~
Update Radiant Tale with choices hook

Update Radiant Tale with choices hook, add Fanfare

---

NS_010032300C562000_LoverPretend.js

Add LoverPretend / Lover Pretend

Add LoverPretend

---

NS_01001A500AD6A000_Norn9_Norn_Nonette_LOFN.js

Add Norn9 \~Norn + Nonette\~ LOFN

Add Norn9 LOFN

---

PSVita_PCSG00808_Yuukyuu_no_Tierblade_Lost_Chronicle.js
PSVita_PCSG01075_Yuukyuu_no_Tierblade_Fragments_of_Memory.js

Add:
Yuukyuu no Tierblade -Lost Chronicle-
Yuukyuu no Tierblade -Fragments of Memory-

Add Yuukyuu no Tierblade games

---

PSVita_PCSG00852_Magic_Kyun_Renaissance.js

Add Magic Kyun! Renaissance #566

Add Magic Kyun! Renaissance

---

PSVita_PCSG01066_Chouchou_Jiken_Lovesodic.js

Add Chouchou Jiken Lovesodic #372

Add Chouchou Jiken Lovesodic

---

PC_Steam_Unity_Higurashi.js
PC_Steam_Unity_Higurashi_Hou.js

Would add support for Higurashi from Steam. I believe it should work on all 8 of the main arcs, although I've only tested in in Onikakushi. Also, Onikakushi is free on Steam, if anyone wants to test this:
[https://store.steampowered.com/app/310360/Higurashi_When_They_Cry_Hou__Ch1_Onikakushi/](https://store.steampowered.com/app/310360/Higurashi_When_They_Cry_Hou__Ch1_Onikakushi/
)
A fair warning that I've only tested this with [07th-Mod](https://07th-mod.com/) installed, and not on the vanilla game.

Add Higurashi Hou / 07th Mod

---

NS_010027300A660000_Shiritsu_Berubara_Gakuen_Versailles_no_Bara_Re_imagination.js

Add Shiritsu Berubara Gakuen \~Versailles no Bara Re*imagination\~ #411 #561

Add Shiritsu Berubara Gakuen ~Versailles no Bara Re*imagination~

---

PSVita_PCSG00477_Hyakka_Yakou.js

Add Hyakka Yakou

---

PSVita_PCSG00855_Hana_Oboro_Sengoku-den_Ranki.js

Add Hana Oboro \~Sengoku-den Ranki\~ #584

Add Hana Oboro ~Sengoku-den Ranki~

---

PC_Steam_Unity_Inverted_Angel.js

may update after i keep playing the game

Add Inverted Angel

---

NS_0100E4000F616000_Himehibi_Another_Princess_Days_White_or_Black.js
NS_0100F8D0129F4000_Himehibi_Princess_Days.js

Add:
Himehibi -Princess Days- #559 
Himehibi Another Princess Days -White or Black- #560

Add Himehibi games

---

NS_01000BB01CB8A000_Trouble_Magia_Wakeari_Shoujo_wa_Mirai_o_Kachitoru_Tame_ni_Ikoku_no_Mahou_Gakkou_e_Ryuugaku_Shimasu.js

Add Trouble Magia \~Wakeari Shoujo wa Mirai o Kachitoru Tame ni Ikoku no Mahou Gakkou e Ryuugaku Shimasu\~ #586

Add Trouble Magia

---

NS_01001BA01EBFC000_Moeyo_Otome_Doushi_Kayuu_Koigatari.js

Add Moeyo! Otome Doushi \~Kayuu Koigatari\~

Add Moeyo! Otome Doushi ~Kayuu Koigatari~

---

PSVita_PCSG00815_PsychicEmotion6.js

Add PsychicEmotion6

---

NS_01000E701DAE8000_Natsuzora_no_Monologue.js

The script was made as if the game was 32-bit, but the game is actually 64-bit. Made some changes to correct the difference and removed the giant fullwidth whitespace between name and dialogue texts.

Fix Natsuzora no Monologue for Ryujinx

---

NS_01008A001C79A000_Kurenai_no_Homura_Sanada_Ninpou_Chou.js
NS_0100E8E016D82000_KLAP_Kind_Love_and_Punish.js

Add NS Kurenai no Homura Sanada Ninpou Chou  #361
Add NS KLAP!! ~Kind Love And Punish~ #237 #613

Add NS Kurenai no Homura Sanada Ninpou Chou & KLAP!!

---

NS_01007FD00DB20000_Katakoi_Contrast.js

Add NS Katakoi Contrast -collection of branch-  #355 #562

Add NS Katakoi Contrast

---

PC_Unity_Kyokkou_no_Marriage.js

Add Script for "Kyokkou no Marriage" by ensemble

Add Kyokkou no Marriage

---

NS_0100F9D00C186000_Olympia_Soiree.js

Replaced text hook for another that displays player name if they chose their own name, added choices hook, and disabled the cursed popup dictionary hook from messily outputting the choices' text.

Update Olympia Soiree

---

PC_Steam_Unity_SeaBed.js

Added SeaBed

---

NS_01005BA00F486000_Crayon_Shin_chan_Ora_to_Hakase_no_Natsuyasumi.js

https://github.com/0xDC00/scripts/issues/651

Add NS - Crayon Shin-chan Ora to Hakase no Natsuyasumi

---

3DS_Japan_Monster_Strike.js
3DS_USA_Shin_Megami_Tensei_Devil_Survivor_2_Record_Breaker.js
libCitra.js

Update libCitra.js
Standardize 3DS naming
Add Monster Strike

Update 3DS support

---

3DS_Japan_Monster_Strike.js
3DS_Japan_Puzzle_Dragons_X_Ryuu_no_Shou.js

Add Puzzle & Dragons X: Ryuu no Shou
Change space to ideographic space in Monster Strike

Add Puzzle & Dragons X: Ryuu no Shou

---

3DS_Japan_Tales_of_the_World_Reve_Unitia.js
3DS_Japan_Toushin_Toshi_Girls_Gift_RPG.js

Toushin Toshi: Girls Gift RPG (Japan)
Tales of the World: Reve Unitia (Japan)
Closes #166

Tales of the World: Reve Unitia (Japan), Tales of the World: Reve Unitia (Japan)

---

3DS_Japan_Gaist_Crusher_God.js

Gaist Crusher God (Japan)
Closes #681

Gaist Crusher God (Japan)

---

PSP_ULJM06302-3_Seishun_Hajimemashita.js
PSP_ULJM6064_Armen_Noir_Portable.js

- Add PSP Seishun Hajimemashita! #665
- Add PSP Armen Noir Portable

Add PSP scripts

---

NS_01008A001C79A000_Kurenai_no_Homura_Sanada_Ninpou_Chou.js
NS_0100B5801D7CE000_Kannagi_no_Mori_Satsukiame_Tsuzuri.js
NS_0100D57014692000_Hakuouki_Reimeiroku.js
NS_0100E8E016D82000_KLAP_Kind_Love_and_Punish.js
PSP_ULJM05447_Will_O'_Wisp_Portable.js
PSP_ULJM06302-3_Seishun_Hajimemashita.js
PSP_ULJM6064_Armen_Noir_Portable.js

- Add new scripts for : 
PSP Will O' Wisp Portable
NS Hakuouki Reimeiroku
NS Kannagi no Mori Satsukiame Tsuzuri
- Clean up some old scripts to look neater.

Add new scripts & clean up some old scripts

---

PS2_SLPM66302_CLANNAD.js
PS2_SLPS25332_SNOW.js

Filtering was bad, Snow was spitting out garbage from the decoder at the end of some lines, also add MC names

Fix PS2 scripts

---

PS2_SLPM66045_My_Merry_May_with_be.js

My Merry May with be script for PCSX2

add PS2_SLPM66045_My_Merry_May_with_be.js

---

PS2_SLPM65914_NANA.js
PS2_SLPS25547_Ichigo_Marshmallow.js
PS2_SLPS25677_BLOOD+_One_Night_Kiss.js

Adding:
NANA
Blood+ One Night Kiss
Ichigo Marshmallow

Add three PCSX2 scripts, 

---

PC_Steam_Granblue_Fantasy_Relink.js

Add Granblue Fantasy Relink

---

PSVita_PCSG00510_Starry_Sky_Spring_Stories.js
PSVita_PCSG00916_Starry_Sky_Summer_Stories.js
PSVita_PCSG00917_Starry_Sky_Autumn_Stories.js
PSVita_PCSG00918_Starry_Sky_Winter_Stories.js

Add:
Starry☆Sky \~Spring Stories~
Starry☆Sky \~Summer Stories~
Starry☆Sky \~Autumn Stories~
Starry☆Sky \~Winter Stories~
Closes #309

Add Starry Sky Series

---

PSP_ULJM06129_Toki_no_Kizuna_Sekigahara_Kitan.js
PSP_ULJM06301_Toki_no_Kizuna_Hanayuitsuzuri.js

Add:
Toki no Kizuna Sekigahara Kitan
Toki no Kizuna Hanayuitsuzuri

Add Toki no Kizuna games

---

PSVita_PCSG00420_DRAMAtical_Murder_recode.js
PSVita_PCSG00667_LoveQuiz_Koi_Suru_Otome_no_Final_Answer.js
PSVita_PCSG01019_Tsumikui _Sen_no_Noroi_Sen_no_Inori.js
PSVita_PCSG01046_Usotsuki_Shangri_La.js

Add Vita scripts:
- DRAMAtical Murder re:code
- Tsumikui -Sen no Noroi, Sen no Inori-
- Love:Quiz -Koi Suru Otome no Final Answer-
- Usotsuki Shangri-La

Add Vita scripts

---

NS_01009CB01BD36000_Yohane_the_Parhelion_BLAZE_in_the_DEEPBLUE.js

Steam version was a bitch, so I went with the Switch version.

Add YOHANE THE PARHELION -BLAZE in the DEEPBLUE- (Switch)

---

NS_01002BE0118AE000_OZMAFIA!!_vivace.js

Add OZMAFIA!! -vivace-

---

NS_0100AAF020664000_Apathy_Danshikou_de_Atta_Kowai_Hanashi.js
NS_0100BBA00B23E000_Yoshiwara_Higanbana_Kuon_no_Chigiri.js

Add NS - Apathy Danshikou de Atta Kowai Hanashi
Add NS - Yoshiwara Higanbana Kuon no Chigiri #731

Add NS scripts 

---

PC_Steam_Death_end_reQuest.js
PC_Steam_Death_end_reQuest_2.js

Add Death end re;Quest (PC/Steam)
Add Death end re;Quest 2 (PC/Steam) #408

Add Death end re;Quest 1 & 2 (PC/Steam)

---

3DS_Japan_Metal_Max_4_Gekkou_no_Diva.js

Add Metal Max 4 - Gekkou no Diva (Japan)
Closes #682

Add Metal Max 4 - Gekkou no Diva (Japan)

---

3DS_Japan_Devil_Survivor_2_Record_Breaker.js

Add Devil Survivor 2 Record Breaker (Japan)
Closes #156

Add Devil Survivor 2 Record Breaker (Japan)

---

NS_01008A401FEB6000_Mystery_no_Arukikata.js

Add NS Mystery no Arukikata

---

PC_Steam_Death_end_reQuest.js
PC_Steam_Death_end_reQuest_2.js

Add a few signatures to the first script and minor/insignificant changes to both scripts.

Update Death end re;Quest 1 & 2

---

PC_Steam_Atelier_Sophie_The_Alchemist_of_the_Mysterious_Book_DX.js

Add hooks for special attacks and sound room
Replace hook for rumor names with a better one

Update Atelier Sophie

---

PC_Steam_Death_end_reQuest.js
PC_Steam_Death_end_reQuest_2.js

I forgot to test the scripts with the GOG version of the games. Turns out they work.

Update metadata in Death end re;Quest 1 & 2

---

3DS_Japan_Layton_Kyouju_vs_Gyakuten_Saiban.js

Add Professor Layton vs. Phoenix Wright (Japan)

Script for Professor Layton vs. Phoenix Wright

---

PC_Steam_Unity_Urban_Myth_Dissolution_Center.js

Add Urban Myth Dissolution Center
Closes #763

Add Urban Myth Dissolution Center

---

PSVita_PCSG00172_Kajiri_Kamui_Kagura_Akebono_no_Hikari.js

Add Kajiri Kamui Kagura Akebono no Hikari

Add PSVita Script

---

PC_Steam_SENRAN_KAGURA_Bon_Appetit!_Full_Course.js
PC_Steam_SENRAN_KAGURA_Burst_ReNewal.js
PC_Steam_SENRAN_KAGURA_ESTIVAL_VERSUS.js
PC_Steam_SENRAN_KAGURA_Peach_Beach_Splash.js
PC_Steam_SENRAN_KAGURA_Reflexions.js
PC_Steam_SENRAN_KAGURA_SHINOVI_VERSUS.js

Burst Re:Newal, SHINOVI VERSUS, ESTIVAL VERSUS, Bon Appétit! - Full Course, Peach Beach Splash, and Reflexions

Add 6 Senran Kagura games (all PC)

---

NS_0100F7E00DFC8000_Cupid_Parasite.js

Add separate hooks for name and text

Update Cupid Parasite

---

libVita3k.js

Now supports v0.1.9 3520 to v0.2.0 3742

Update libVita3k to support latest builds

---

PC_Cursed_Futanari_Ring.js
PC_Steam Superdimension_Neptune_VS_Sega_Hard_Girls.js
PC_Steam_Hyperdimension_Neptunia_ReBirth1.js
PC_Steam_Hyperdimension_Neptunia_ReBirth2_Sisters_Generation.js
PC_Steam_Hyperdimension_Neptunia_ReBirth3_V_Generation.js
PC_Steam_Megadimension_Neptunia_VIIR.js
PC_Steam_Unity_Neptunia_Sisters_VS_Sisters.js

Hyperdimension Neptunia Re;Birth1, Hyperdimension Neptunia Re;Birth2, Hyperdimension Neptunia Re;Birth3, Megadimension Neptunia VIIR, Superdimension Neptune VS Sega Hard Girls, and Neptunia Sisters VS Sisters.
And moving the warning in FutaHime at the bottom, so it's visible in Agent.

Add six Neptunia games (PC)

---

NS_010048101D49E000_Re;quartz_Raid.js
NS_0100B6501FE4C000_Kenka_Banchou_Otome_Double_Pack.js

- add NS Kenka Banchou Otome Double Pack
- add NS Re;quartz Raid

Add NS scripts

---

PC_Steam_KiriKiriZ_Tsuyuchiru_Letter_Umi_to_Shiori_ni_Amaoto_o.js

Despite saving the hooks in Textractor I'd still have to find new ones each time I launch the game, so I figured I might as well.

Add Tsuyuchiru Letter

---

PSVita_PCSG00745_Scared_Rider_Xechs_Rev.js

Add Scared Rider Xechs Rev.

---

NS_01000C7019E1C000_Wand_of_Fortune_R_for_Nintendo_Switch.js

Replaced dialogue hook since it was getting called twice every time and didn't have the player's custom name.
Changed styling.

Update Wand of Fortune R

---

PC_Steam_Ni.No.Kuni.Wrath.Of.The.White.Witch.Remastered.js

This makes for a much nicer experience because the previous implementation would hide repeat visits to the same menu pages, and character names would also get lost during conversation. Been using this for the last month and it's resulted in a much nicer experience for me than the old approach!
The lack of a monotonic clock API in the JS runtime is a bit unfortunate, but with the guard against time suddenly going backwards this should be good enough.

Ni no Kuni: Filter repeat text based on time instead of last occurences

---

PC_Steam_LUNAR_1_REMASTERED.js

The first game from the remastered collection that released yesterday. I'll do the second one if I get to it some day.
Hooks all the text on the screen (dialogues and menus) and cutscene subtitles.
Some special characters are not decoded correctly. Example:
I don't really feel like fixing it is worth the time.

add LUNAR 1 Remastered

---

PC_Steam_Nier_Replicant.js

I am in no way an expert with making these scripts, fixes #429

Add Nier Replicant Script

---

PC_Steam_The_Hundred_Line_Last_Defense_Academy.js

Needs more time in the oven
Closes #831

Add The Hundred Line -Last Defense Academy-

---

NS_0100273013ECA000_Summer_Pockets_REFLECTION_BLUE.js

Closes #194 
Will revisit for cleaner hooks

Add Summer Pockets REFLECTION BLUE

---

NS_0100E9801CAC2000_OVER_REQUIEMZ.js

Add OVER REQUIEMZ

---

NS_0100D4601FD60000_Soukoku_no_Kusabi_Hiiro_no_Kakera_Tamayorihime_Kitan.js

Add NS Soukoku no Kusabi

---

PC_Steam_Ao_no_Kiseki.js
PC_Steam_Zero_no_Kiseki.js

Add Zero no Kiseki and Ao no Kiseki (PC)

---

PC_Steam_Unity_Sumire.js

Works with VN-style dialogue and floating speech bubbles
Minigames and menus are missing translations but I was able to complete the game without them.

add Sumire gamescript

---

PC_Steam_Hajimari_no_Kiseki.js
PC_Steam_Sen_no_Kiseki_III.js
PC_Steam_Sen_no_Kiseki_IV.js
PSVita_PCSG00488_Sora_no_Kiseki_FC_Evolution.js
PSVita_PCSG00489_Sora_no_Kiseki_SC_Evolution.js
PSVita_PCSG00490_Sora_no_Kiseki_the_3rd_Evolution.js

And minor updates to other Kiseki scripts.
I just realized there already was a Hajimari no Kiseki script. Oops.

Add/update Hajimari no Kiseki (PC)

---

NS_0100DA2019044000_Ketsugou_Danshi_Elements_with_Emotions.js

Add Ketsugou Danshi -Elements with Emotions- for Switch

Add Ketsugou Danshi for Switch

---

PC_Steam_Ao_no_Kiseki.js
PC_Steam_Hajimari_no_Kiseki.js
PC_Steam_Sen_no_Kiseki.js
PC_Steam_Sen_no_Kiseki_II.js
PC_Steam_Sen_no_Kiseki_III.js
PC_Steam_Sen_no_Kiseki_IV.js
PC_Steam_Zero_no_Kiseki.js

I've been wanting to update the readString functions in the Zero and Ao scripts for a bit to make them more like the others. And while I was at it, I thought I might as well try to fix some issues and try to find more hooks I either didn't think about before or somehow couldn't manage to find for other scripts.

Update some Kiseki scripts

---

NS_01006A60216CA000_Yuukyuu_no_Tierblade.js

Add Yuukyuu no Tierblade (Switch)

---

PC_Steam_Sora_no_Kiseki_the_1st.js

I will update it if the full game release breaks the script.

Add Sora no Kiseki the 1st (PC)

---

PC_Steam_Unreal_Octopath_Traveler.js

Add Octopath Traveler (Steam)
